name: CI - Validate Bash Script

on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Bash script exists
        run: ls scripts/install-nginx.sh

      - name: Run ShellCheck on script
        uses: ludeeus/action-shellcheck@master
        with:
          args: scripts/install-nginx.sh
